### ISSUE TITLE
add multipart support in rest client

### ISSUE THREAD

**Issue by neo7337** [nandlabs/go-commons#20]

**Comment by nandagopalan** [comment]
May be a Request#SetMultiPartFile(filename, params map[string]string) can be created .

**Comment by nandagopalan** [comment]
@neo7337  Does It make sense to use vfs here ?

**Comment by neo7337** [comment]
Don't think so vfs involvement should be necessary, we are just adding the files to the request to be read by the server.
Adding the files to the request can be something like this:-
1. read the file from the client location
2. create a stream
3. via reader set the file stream to the multipart object with the provided param name of the file

lemme know if I am making sense!

**Comment by nandagopalan** [comment]
The only reason I was thinking vfs is because then it'll allow remote  to remote file upload. It's going to be tricky but we can park it and support local file for the time being.
