### ISSUE TITLE
Add Test Cases fro VFS

### ISSUE THREAD

**Issue by nandagopalan** [nandlabs/go-commons#43]
The VFS Package does not have tests. Need to add test cases for the same.

**Comment by nandagopalan** [comment]
@Neo Are you able to pick this up as it will help in go-aws-commons

**Comment by neo7337** [comment]
Questions/Information @nandagopalan 

1. os.Create() will create a file if no file type is present, ideally it should create a directory
2. Added a new interface -> 
    //RemoveDir will delete the target directory provided in the input URL
    RemoveDir(u *url.URL) error
3. should we implement the similar -> os.RemoveAll() function as well 9to remove the directory with it's content similar to `rm -r`?
4. Unable to create the relative folders for the unit test cases using the file url example -> `file://./tests/abc.txt`. what should the expected URL and if it's correct, are we expecting a change in the code?
