### ISSUE TITLE
Rest Client HTTP/HTTPS env proxy

### ISSUE THREAD

**Issue by nandagopalan** [nandlabs/go-commons#50]
The rest.Client#UseEnvProxy currently does not specify if the  proxy is for HTTP or HTTPs update the function to include the protocol as well.

**Comment by rajkumarGosavi** [comment]
Hi @neo7337 @nandagopalan 
I would like to implement this.

Can you please guide me with the following doubts:

1. Do we need to now pass the protocol as a parameter in the `UseEnvProxy` function?
2. If the above is true then given that the protocol is `https` do we need to set the TLSConfig in the `SetProxy` function?

Let me know if I am missing something here.

Thank you!!

**Comment by nandagopalan** [comment]
Hi @rajkumarGosavi, 
Thank you for your interest. I have assigned this issue to you.
The idea is to just ensure that there are options for using different proxies for http and https. And each may have a different credentials too. ( we will stick to basic auth here)


Upon revisiting the code , This appears to be a  complete revamp of the proxy setting in the library.
At the moment the code [here](https://github.com/nandlabs/go-commons/blob/dc763df5cef75f151866cd782644bd0b561d0e57/clients/rest/rest.go#L116)  appears to be incorrect as its using the builtin ProxyURL returns a proxy function (for use in a Transport) that always returns the same URL. as per the documentation. This hasn't been tested out.

As a part of this issue we need to.

1) Update Client Struct to hold config for both http and https proxy details along with credentials for them (currently one one credential supported allow both of them to be used). This can be done by leveraging the Builtin [Proxy Config](https://pkg.go.dev/golang.org/x/net/http/httpproxy#Config) and renaming the current proxy credential to httpProxyCredential and httpsProxyCredential respectively. The config member of the client will be  defaulted  to [Environment configuration](https://pkg.go.dev/golang.org/x/net/http/httpproxy#FromEnvironment). 

2. When the  [Transport](https://github.com/nandlabs/go-commons/blob/dc763df5cef75f151866cd782644bd0b561d0e57/clients/rest/rest.go#L42) is initialised, set the value to the c.config.ProxyFunc() (refer to doco [here ]([ProxyFunc](https://cs.opensource.google/go/x/net/+/v0.15.0:http/httpproxy/proxy.go;l=117) 

3. Add the protocol as as enum  variadic parameter to with enum type ( Http and Https) to the following signature

> [set proxy](https://github.com/nandlabs/go-commons/blob/dc763df5cef75f151866cd782644bd0b561d0e57/clients/rest/rest.go#L116)

> https://github.com/nandlabs/go-commons/blob/dc763df5cef75f151866cd782644bd0b561d0e57/clients/rest/rest.go#L174

The above 2 functions will update the client#Config struct with appropriate values ,set credentials per type as well as update the [httpClient](https://github.com/nandlabs/go-commons/blob/dc763df5cef75f151866cd782644bd0b561d0e57/clients/rest/rest.go#L34C2-L34C12).Transport#Proxy to a new function by invoking client.proxyConfig#ProxyFunc()

4. We also need to update the [proxy auth header](https://github.com/nandlabs/go-commons/blob/dc763df5cef75f151866cd782644bd0b561d0e57/clients/rest/rest.go#L223) for the outbound request based on the request url protocol.

**Comment by nandagopalan** [comment]
Closing this issue.
