### ISSUE TITLE
Create a HTTP Client interface tailored for REST APIs

### ISSUE THREAD

**Issue by nandagopalan** [nandlabs/go-commons#7]
Need a new HTTP Client interface that encapsulates all operations for the REST API such as
1. Authentication

- Basic
- Implicit token generation for token based auth 
- Auto renewal of tokens

3. Codec/Data Transformation
4. SSL and  External certificate/key store usage
5. Retries
6. Circuit Breaker implementation
7. HTTP redirect follows with limits
8. Reusing and Caching of clients
9. Error Handling

**Comment by neo7337** [comment]
@nandagopalan do we want to write our own client or build a wrapper on the default net/http client implementation?

**Comment by nandagopalan** [comment]
Moved to turbo-client

**Comment by nandagopalan** [comment]
Initial version with the following support has been added and merged to main https://github.com/nandlabs/go-commons/pull/15

1. Codec Data Transformation 
2. Retries
3. Circuit Breaker 
4. Caching of clients (default http.Client Caching leveraged)

**Comment by nandagopalan** [comment]
https://github.com/nandlabs/go-commons/pull/15 issues resolved in the subsequent https://github.com/nandlabs/go-commons/pull/16

**Comment by nandagopalan** [comment]
Remaining features will have there own issues
