### ISSUE TITLE
VFile Create new DeleteAll Fn

### ISSUE THREAD

**Issue by nandagopalan** [nandlabs/go-commons#77]
The current VFile interface defines a function Delete() that is supposed to delete file or directory. However this is confusing to use.

1. Define a new function named DeleteAll in the VFile interface. This function will delete a file or directory with all its contents.
2. Update the defn of Delete() fn to just delete file and throw error in case of directory
3. Update the DeleteMatching() fn to check if the vFile object resolved by the filter is a directory ?
>  1. If it s a directory call the resolvedFile.DeleteAll()
> 2. If its a File call resolvedFile.Delete()

**Comment by neo7337** [comment]
Can we do like call the Delete() fnc and inside that if we check whether the location is a directory or not?

> If it's a directory then invoke DeleteAll() and delete the directory
> Otherwise delete the file
