### ISSUE TITLE
Move library to golly

### ISSUE THREAD

**Issue by nandagopalan** [nandlabs/go-commons#78]
go-commons is a very boring name. Let's Rename the library to golly .
 Its an acronym that loosely means Go Open Source Library
1. Update the project name
2. Update Go Mod  name
3. Update Main Documentation Read Me

**Comment by neo7337** [comment]
use golly.nandlabs.io

**Comment by nandagopalan** [comment]
Given other dependants of this library, we have decided not to rename and merge this with https://github.com/nandlabs/golly
